### ISSUE TITLE
Admin & Supervisor role is hardcoded by primary key (id)

### ISSUE THREAD

**Issue by jlsjonas** [enso-ui/ui#12]
This is  a **bug | question**. (it depends 😁)

### Prerequisites
Yes

### Description

https://github.com/enso-ui/ui/blob/39e8c9ef59496fb4f11cfd4d8047349339453a4b/src/core/components/navbar/IO.vue#L40-L42

Seems to assume the Admin & Supervisor role to be <= 2

https://github.com/laravel-enso/IO/blob/master/src/BroadcastServiceProvider.php#L16-L18

The back-end correctly uses the _right_ setting

**Comment by aocneanu** [comment]
`operations` is a private channel for admins and supervisors, so they can see all other users IO
`operations.{userId}` is a private channel for users with lower roles where they can see only their activity

**Comment by jlsjonas** [comment]
I understand, the _issue_ is that FE expects admin & supervisor role to be <=2

Back-end does correctly use the _actual_ ids... and writing this I see that the id's are actually hardcoded in rolemanager (but overwritable in User).

in our case, the issue is 2-part:
- role <=2 isn't admin by default (this can be easily worked around though, but...)
- We have a multitude of admin-like roles (multiple _levels_, multiple _areas_).

Purely for IO-operations we'd actually limit global notifications to a _superadmin_, so that should be fine. However (though I guess this will be at first a back-end side change) I believe we should avoid assuming 1&2 for admin & supervisor.

Suggestion/thought on this: Introduce an extra `admin_level` int on the role table, attached to an `AdminLevel` Enum (this allows most flexibility, also in the future).  
Here, Admin could remain 1 & Supervisor 2, allowing only minor changes on the front-end (checking for admin_level instead of role_id)

**Comment by aocneanu** [comment]
We'll think this thoroughly on the next be refactor.
