### ISSUE TITLE
Settings-menu is always open if reduce-motion setting on OS is on in latest Chrome

### ISSUE THREAD

**Issue by paulmaessen** [enso-ui/ui#18]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
In the latest Chrome-version (version 74) there is a problem that the settings-menu on the right side of the page is always open if the OS-setting for reduce motion is selected.
This causes issues with the buttons that you can not use  because they are hidden underneath this m enu.  (see attached screenshots)

### Steps to Reproduce
Open the Laravel Enso Application
Open the Users-table (screenshot 1)
Enable in your OS the reduce-motion setting:
  - OSX: Settings > General > Accessibility > Select Reduce Motion
  - IOS: System Preferences > Accessibility > Display > Select Reduce Motion
  - Windows: Settings > Ease of Access > Deselect Show animations in Window 

As you can see now the Settings-menu is opened and cannot be closed so you can not edit the records in the table (screenshot 2)

### Expected behavior
The expected behavior is that this menu can be closed and opened independent from the OS-settings.

### Actual behavior
The settings menu is opened always and cannot be closed if reduced motion is enabled in the OS.

[
<img width="1828" alt="ScreenShot1" src="https://user-images.githubusercontent.com/6616793/58428129-dbf70600-80a1-11e9-9bd5-2124a10eef14.png">
<img width="1828" alt="ScreenShot2" src="https://user-images.githubusercontent.com/6616793/58428165-f03b0300-80a1-11e9-88e5-8c5e8e59809c.png">

](url)

**Comment by paulmaessen** [comment]
Additional comment: 
The menu on the left-side is not influenced by the Reduced Motion-setting of the OS.

**Comment by aocneanu** [comment]
Yes, that's true, the settings menu uses transitions. The same applies to all the transitions in the application, and it's not a bug.

**Comment by paulmaessen** [comment]
Hi Adrian, The fact that the transitions do not work is not a bug indeed. The problem (bug) is the fact that the settings menu is collapsed and you are not able to use the buttons underneath it.

So the issue here is that depending on this OS-setting you can not use the tables. I assume that the menu on the right side also uses transitions and these do work independent from this setting in the OS

**Comment by paulmaessen** [comment]
This can be solved by updating to the latest version of animate.css (3.7.2) So this issue can be closed
