### ISSUE TITLE
Gender on profile page not displayed (enums.genders not working?)

### ISSUE THREAD

**Issue by mauthi** [enso-ui/ui#22]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

If I open the profile page I get the following:
![image](https://user-images.githubusercontent.com/7204559/59935713-b1089380-944e-11e9-8364-9f832ca6111d.png)

No error or something else.

### Steps to Reproduce
-

### Expected behavior

In `@enso-ui/ui/src/bulma/pages/administration/users/components/UserProfile.vue` on Line 139 `profile.person.gender` has the value 2 and `enums.genders._get(2)` should return `male`.

### Actual behavior

In `@enso-ui/ui/src/bulma/pages/administration/users/components/UserProfile.vue` on Line 139 `profile.person.gender` has the value 2 but `enums.genders._get(2)` does not return anything.

**Comment by aocneanu** [comment]
That's odd,

Could you check in vue devtools / console the output of `$vm0.$store.state.enums.genders._get(2)`?

**Comment by mauthi** [comment]
> Could you check in vue devtools / console the output of $vm0.$store.state.enums.genders._get(2)?

Result:
![image](https://user-images.githubusercontent.com/7204559/60187709-52685e80-982e-11e9-8cae-868d21931205.png)

**Comment by aocneanu** [comment]
I really cannot reproduce this one. I tried locally, on laravel-enso.com and it works as expected.

Maybe you did something to customize the `Enum.js` ? Or maybe it has something to do with localisation?

`$vm0.$store.state.enums.genders._get("2")` is still undefined?

**Comment by mauthi** [comment]
I tried to reproduce this on laravel-enso.com and there it's also not working in German. So I think that it has todo something with localisation.

Please compare the following screenshots:

EN
![image](https://user-images.githubusercontent.com/7204559/60717284-b8856d80-9f21-11e9-9f95-6be04b9839e3.png)

DE
![image](https://user-images.githubusercontent.com/7204559/60717306-c5a25c80-9f21-11e9-8c8d-938ea1d28cfa.png)

**Comment by aocneanu** [comment]
Ok, will look into it
