### ISSUE TITLE
Calendar issue in Brazilian Portuguese 

### ISSUE THREAD

**Issue by boing6000** [enso-ui/ui#26]
This is  a **bug | feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Calendar not show when language in Brazilian Portuguese

### Expected behavior
Calendar appear in this language

### Actual behavior
Component not render

In the documentation of vue-cal the language code need to be "pt-br" in enso is "br"

**Comment by aocneanu** [comment]
I guess this was fixed in vuecal2

>Currently available languages are Arabic, Bosnian, Bulgarian, Catalan, Czech, Chinese (Simplified), Chinese (Traditional), Croatian, Danish, Dutch, English, Farsi, French, Georgian, German, Hebrew, Hungarian, Italian, Japanese, Norwegian, Polish, Portuguese Brasilian, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swedish, Turkish, Ukrainian, Vietnamese.
If you are interested in providing a language support please do a pull request with a json file into the i18n directory.
this is what a language json looks like.
