### ISSUE TITLE
Error: "Route Error: "user" key is required for route "administration.users.edit""

### ISSUE THREAD

**Issue by robbykrlos** [enso-ui/ui#28]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
After yarn upgrade from 1.3.31 to 1.3.43 on all edit actions ("pen icon") i press on local entities or enso entities I get:
```
[Vue warn]: Error in nextTick: "Error: Route Error: "user" key is required for route "administration.users.edit""
VueJS 6
        warn
        logError
        globalHandleError
        handleError
        nextTick
        flushCallbacks
```
and 
```
Error: "Route Error: "user" key is required for route "administration.users.edit""
    throwMissingKeyError Route.js:77
    optionalParam Route.js:62
    fillParam Route.js:48
    fillParams Route.js:35
    maybeCallNative vuedraggable.common.js:351
    a481 vuedraggable.common.js:1929
    exports vuedraggable.common.js:365
    replace vuedraggable.common.js:1923
    fillParams Route.js:33
    buildUrl Route.js:21
    Route Route.js:10
    route route.js:5
    _default EnsoForm.vue:42
    VueJS 103
vue.common.dev.js:1893
    VueJS 5
```

Also it seems that the URL changes to main URL, and does not go to /adminitrations/users/1/edit

Also, I'm not 100% sure it comes from the actual upgrade, I had also some local changes but nothing that may affect enso core.

Also I was not sure if this is a ensi-ui/ui bug, of enso-ui/forms - since the error seems to be related to EnsoForm.

**Comment by aocneanu** [comment]
Do you have the latest backend?

**Comment by robbykrlos** [comment]
> Do you have the latest backend?

Nope. Will update 3.3.5 to 3.3.6. Sorry. Thanks.
