### ISSUE TITLE
Unknown custom element <documents> in form slot

### ISSUE THREAD

**Issue by jlsjonas** [enso-ui/ui#3]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Having a `<documents>` inside a custom slot inside `enso-form` seems to cause `<confirmation>` & `<modal>`, residing in `File.Vue` & `Url.vue` respectively, to become _unknown_.
![image](https://user-images.githubusercontent.com/932193/54920684-22927d80-4f04-11e9-8068-1863fc8c8e06.png)

Causing a hot reload of either component _fixes_ the issue, which makes me think towards a circular reference issue (which is plausible for Modal, not so sure about Confirmation though)

### Steps to Reproduce
1. Add a <documents> in a custom slot in an <enso-form>
2. Notice above behaviour

### Expected behavior

Component to load in correctly

### Actual behavior

_unknown_ component, causing errors & visual discrepancies

**Comment by aocneanu** [comment]
make sure that you have all `@enso-io` vendors extracted in [webpack.min.js](https://github.com/laravel-enso/Enso/blob/master/webpack.mix.js)

**Comment by jlsjonas** [comment]
Oh wauw... sorry 😅 
looks like the @enso-ui part of my webpack change disappeared with one of the updates 😬
