### ISSUE TITLE
Bug background color menu mobile

### ISSUE THREAD

**Issue by heyner29** [enso-ui/ui#43]
This is  a bug.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
With the new update, the appearance of the mobile menu was broken.
As it does not have a background color, it does not overlap the content of the page.

![Screenshot_20200330-075529](https://user-images.githubusercontent.com/12703614/77923194-b27dac80-7267-11ea-9113-e6fa1630b85d.png)

**Comment by aocneanu** [comment]
lol, looks slick :D
