### ISSUE TITLE
Version 3 build errors

### ISSUE THREAD

**Issue by curtisdelicata** [enso-ui/ui#52]
This is  a **bug **

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
Multiple errors about flex-basis: auto needing an identifier. Tried to upgrade css packages according to the package lock in the pull request for v4.

**Comment by raftx24** [comment]
Hi @curtisdelicata 
Can you send me the error log?

**Comment by curtisdelicata** [comment]
DONE  No lint errors found!

/  Building legacy bundle for production...

 ERROR  Failed to compile with 4 errors                                03:01:35

 error  in ./node_modules/@enso-ui/themes/bulma/dark-rtl.lazy.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
63 │         flex-basis: auto
   │                    ^
   ╵
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 63:
20  calendar()
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 222
:3  @import
  node_modules\@enso-ui\themes\bulma\extensions.sass 2:9
    @import
  C:\Users\j\PhpstormProjects\genealogy\client\node_modules\@enso-ui\themes\bul
ma\dark-rtl.lazy.scss 14:9
                  root stylesheet

 @ ./node_modules/@enso-ui/themes/bulma/dark-rtl.lazy.scss 2:26-270
 @ ./node_modules/@enso-ui/themes/bulma sync nonrecursive .*\.lazy\.scss$
 @ ./node_modules/@enso-ui/ui/src/modules/store/layout.js
 @ ./node_modules/@enso-ui/ui/src/modules/store sync nonrecursive .*\.js$
 @ ./node_modules/@enso-ui/ui/src/modules/store.js
 @ ./src/js/store.js
 @ ./src/js/enso.js
 @ multi ./src/js/enso.js

 error  in ./node_modules/@enso-ui/themes/bulma/dark.lazy.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
63 │         flex-basis: auto
   │                    ^
   ╵
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 63:
20  calendar()
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 222
:3  @import
  node_modules\@enso-ui\themes\bulma\extensions.sass 2:9
    @import
  C:\Users\j\PhpstormProjects\genealogy\client\node_modules\@enso-ui\themes\bul
ma\dark.lazy.scss 14:9
              root stylesheet

 @ ./node_modules/@enso-ui/themes/bulma/dark.lazy.scss 2:26-266
 @ ./node_modules/@enso-ui/themes/bulma sync nonrecursive .*\.lazy\.scss$
 @ ./node_modules/@enso-ui/ui/src/modules/store/layout.js
 @ ./node_modules/@enso-ui/ui/src/modules/store sync nonrecursive .*\.js$
 @ ./node_modules/@enso-ui/ui/src/modules/store.js
 @ ./src/js/store.js
 @ ./src/js/enso.js
 @ multi ./src/js/enso.js

 error  in ./node_modules/@enso-ui/themes/bulma/light-rtl.lazy.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
63 │         flex-basis: auto
   │                    ^
   ╵
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 63:
20  calendar()
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 222
:3  @import
  node_modules\@enso-ui\themes\bulma\extensions.sass 2:9
    @import
  C:\Users\j\PhpstormProjects\genealogy\client\node_modules\@enso-ui\themes\bul
ma\light-rtl.lazy.scss 14:9
                   root stylesheet

 @ ./node_modules/@enso-ui/themes/bulma/light-rtl.lazy.scss 2:26-271
 @ ./node_modules/@enso-ui/themes/bulma sync nonrecursive .*\.lazy\.scss$
 @ ./node_modules/@enso-ui/ui/src/modules/store/layout.js
 @ ./node_modules/@enso-ui/ui/src/modules/store sync nonrecursive .*\.js$
 @ ./node_modules/@enso-ui/ui/src/modules/store.js
 @ ./src/js/store.js
 @ ./src/js/enso.js
 @ multi ./src/js/enso.js

 error  in ./node_modules/@enso-ui/themes/bulma/light.lazy.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
63 │         flex-basis: auto
   │                    ^
   ╵
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 63:
20  calendar()
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 222
:3  @import
  node_modules\@enso-ui\themes\bulma\extensions.sass 2:9
    @import
  C:\Users\j\PhpstormProjects\genealogy\client\node_modules\@enso-ui\themes\bul
ma\light.lazy.scss 14:9
               root stylesheet

 @ ./node_modules/@enso-ui/themes/bulma/light.lazy.scss 2:26-267
 @ ./node_modules/@enso-ui/themes/bulma sync nonrecursive .*\.lazy\.scss$
 @ ./node_modules/@enso-ui/ui/src/modules/store/layout.js
 @ ./node_modules/@enso-ui/ui/src/modules/store sync nonrecursive .*\.js$
 @ ./node_modules/@enso-ui/ui/src/modules/store.js
 @ ./src/js/store.js
 @ ./src/js/enso.js
 @ multi ./src/js/enso.js

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! genealogy@ build:windows: `cd ../public && rd /s /q js & rd /s /q them
es & rd /s /q themes-rtl & rd /s /q images & cd ../client && node_modules\.bin\
vue-cli-service lint & node_modules\.bin\vue-cli-service build --no-clean --mod
ern --skip-plugins thread-loader`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the genealogy@ build:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional lo
gging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\j\AppData\Roaming\npm-cache\_logs\2020-07-04T02_01_35_401
Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this com
mand.

C:\Users\j\PhpstormProjects\genealogy\client>
C:\Users\j\PhpstormProjects\genealogy\client>
C:\Users\j\PhpstormProjects\genealogy\client>
C:\Users\j\PhpstormProjects\genealogy\client>
C:\Users\j\PhpstormProjects\genealogy\client>yarn build
yarn run v1.22.4
$ npx run-script-os
npx: installed 1 in 3.581s

> genealogy@ build:windows C:\Users\j\PhpstormProjects\genealogy\client
> cd ../public && rd /s /q js & rd /s /q themes & rd /s /q themes-rtl & rd /s /
q images & cd ../client && node_modules\.bin\vue-cli-service lint & node_module
s\.bin\vue-cli-service build --no-clean --modern --skip-plugins thread-loader

The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the file specified.
 DONE  No lint errors found!

\  Building legacy bundle for production...

 ERROR  Failed to compile with 4 errors                                03:16:54

 error  in ./node_modules/@enso-ui/themes/bulma/dark-rtl.lazy.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
63 │         flex-basis: auto
   │                    ^
   ╵
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 63:
20  calendar()
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 222
:3  @import
  node_modules\@enso-ui\themes\bulma\extensions.sass 2:9
    @import
  C:\Users\j\PhpstormProjects\genealogy\client\node_modules\@enso-ui\themes\bul
ma\dark-rtl.lazy.scss 14:9
                  root stylesheet

 @ ./node_modules/@enso-ui/themes/bulma/dark-rtl.lazy.scss 2:26-270
 @ ./node_modules/@enso-ui/themes/bulma sync nonrecursive .*\.lazy\.scss$
 @ ./node_modules/@enso-ui/ui/src/modules/store/layout.js
 @ ./node_modules/@enso-ui/ui/src/modules/store sync nonrecursive .*\.js$
 @ ./node_modules/@enso-ui/ui/src/modules/store.js
 @ ./src/js/store.js
 @ ./src/js/enso.js
 @ multi ./src/js/enso.js

 error  in ./node_modules/@enso-ui/themes/bulma/dark.lazy.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
63 │         flex-basis: auto
   │                    ^
   ╵
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 63:
20  calendar()
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 222
:3  @import
  node_modules\@enso-ui\themes\bulma\extensions.sass 2:9
    @import
  C:\Users\j\PhpstormProjects\genealogy\client\node_modules\@enso-ui\themes\bul
ma\dark.lazy.scss 14:9
              root stylesheet

 @ ./node_modules/@enso-ui/themes/bulma/dark.lazy.scss 2:26-266
 @ ./node_modules/@enso-ui/themes/bulma sync nonrecursive .*\.lazy\.scss$
 @ ./node_modules/@enso-ui/ui/src/modules/store/layout.js
 @ ./node_modules/@enso-ui/ui/src/modules/store sync nonrecursive .*\.js$
 @ ./node_modules/@enso-ui/ui/src/modules/store.js
 @ ./src/js/store.js
 @ ./src/js/enso.js
 @ multi ./src/js/enso.js

 error  in ./node_modules/@enso-ui/themes/bulma/light-rtl.lazy.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
63 │         flex-basis: auto
   │                    ^
   ╵
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 63:
20  calendar()
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 222
:3  @import
  node_modules\@enso-ui\themes\bulma\extensions.sass 2:9
    @import
  C:\Users\j\PhpstormProjects\genealogy\client\node_modules\@enso-ui\themes\bul
ma\light-rtl.lazy.scss 14:9
                   root stylesheet

 @ ./node_modules/@enso-ui/themes/bulma/light-rtl.lazy.scss 2:26-271
 @ ./node_modules/@enso-ui/themes/bulma sync nonrecursive .*\.lazy\.scss$
 @ ./node_modules/@enso-ui/ui/src/modules/store/layout.js
 @ ./node_modules/@enso-ui/ui/src/modules/store sync nonrecursive .*\.js$
 @ ./node_modules/@enso-ui/ui/src/modules/store.js
 @ ./src/js/store.js
 @ ./src/js/enso.js
 @ multi ./src/js/enso.js

 error  in ./node_modules/@enso-ui/themes/bulma/light.lazy.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
63 │         flex-basis: auto
   │                    ^
   ╵
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 63:
20  calendar()
  node_modules\bulma-extensions\bulma-calendar\dist\css\bulma-calendar.sass 222
:3  @import
  node_modules\@enso-ui\themes\bulma\extensions.sass 2:9
    @import
  C:\Users\j\PhpstormProjects\genealogy\client\node_modules\@enso-ui\themes\bul
ma\light.lazy.scss 14:9
               root stylesheet

 @ ./node_modules/@enso-ui/themes/bulma/light.lazy.scss 2:26-267
 @ ./node_modules/@enso-ui/themes/bulma sync nonrecursive .*\.lazy\.scss$
 @ ./node_modules/@enso-ui/ui/src/modules/store/layout.js
 @ ./node_modules/@enso-ui/ui/src/modules/store sync nonrecursive .*\.js$
 @ ./node_modules/@enso-ui/ui/src/modules/store.js
 @ ./src/js/store.js
 @ ./src/js/enso.js
 @ multi ./src/js/enso.js

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! genealogy@ build:windows: `cd ../public && rd /s /q js & rd /s /q them
es & rd /s /q themes-rtl & rd /s /q images & cd ../client && node_modules\.bin\
vue-cli-service lint & node_modules\.bin\vue-cli-service build --no-clean --mod
ern --skip-plugins thread-loader`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the genealogy@ build:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional lo
gging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\j\AppData\Roaming\npm-cache\_logs\2020-07-04T02_16_55_116
Z-debug.log

**Comment by curtisdelicata** [comment]
I'm using latest Node version 14 on Windows. Will test on Ubuntu now too with an earlier version of Node.

**Comment by raftx24** [comment]
i couldn't detect error from your log, but I cloned it in a new server and it was built successfully.

**Comment by curtisdelicata** [comment]
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
╷
63 │ flex-basis: auto
│ ^
╵

That appears in 4 or so files

**Comment by curtisdelicata** [comment]
I'm trying now with Node 13 on Ubuntu.

**Comment by raftx24** [comment]
let me check it with docker too.

**Comment by curtisdelicata** [comment]
Thanks.

**Comment by raftx24** [comment]
@curtisdelicata  I checked it with docker( [new version](https://github.com/laravel-enso/enso/pull/315) ) and it was built.
My node version is `v10.19.0`, and node version of docker is `v10.21.0`; please test with this node version too, and if you still see the error, please tell me.

**Comment by curtisdelicata** [comment]
Can you check latest node as well please? Is it old package version causing it for latest node that's all I could find on Google before posting.

**Comment by curtisdelicata** [comment]
Reason being is version 14 is a lot faster for me to compile with.

**Comment by curtisdelicata** [comment]
Same error on Ubuntu:

genealogia@server01:~/genealogy/client$ node --version
v13.14.0
genealogia@server01:~/genealogy/client$

**Comment by curtisdelicata** [comment]
So do I need to downgrade to version 10 to make it work?

**Comment by raftx24** [comment]
@curtisdelicata I upgraded my node to 14.5 (the latest :-D), and it was built successfully. You may have some other problems. if it's possible for you to push it into some branch, I will check it.

**Comment by curtisdelicata** [comment]
It's all live at https://github.com/modularsoftware/genealogy

I'll donate to the project when I get paid if you can find what is causing it.

**Comment by curtisdelicata** [comment]
It's actually the master branch. I guess should not of been using master in that way.

**Comment by raftx24** [comment]
@curtisdelicata, i found out the problem was related to sass, I created a [PR](https://github.com/modularsoftware/genealogy/pull/1305) for you.

**Comment by curtisdelicata** [comment]
Many thanks. I really appreciate your help.

**Comment by curtisdelicata** [comment]
Legacy built fine. Just waiting for production to finish then if succeeded then I'll close this issue. Thanks for all your help. I'll try to make an opencollective donation as soon as possible but might not be to the 8th July.

**Comment by curtisdelicata** [comment]
Both legacy and modern bundle worked with your pull request merged in. Thanks again.

**Comment by raftx24** [comment]
@curtisdelicata, don't mention it, there isn't any pressure for donation, whenever you can and you like you can do it :)
