### ISSUE TITLE
Previews of page

### ISSUE THREAD

**Issue by curtisdelicata** [enso-ui/ui#53]
This is  a ** feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Previews of the page on sites like Facebook just say Enso and a blank page. Is there anyway to improve or at least use my env name for site instead?

**Comment by raftx24** [comment]
you can use `og` meta tags for this. I think you can do this with the help of Vue locally(you can look at this [topic](https://stackoverflow.com/questions/53285704/set-viewport-meta-tag-in-vue-js-application)). but it's possible to add this to enso too but it depends on @aocneanu opinion :-D

**Comment by curtisdelicata** [comment]
Thanks for the reply. I did search but nothing came up. I'll take a look.

**Comment by curtisdelicata** [comment]
So if I add this to the vue config file I'll get a preview in theory as have not tested as my build is broke as per other issue.  How do I overwrite the 'Enso' page title?

config.plugin('html').tap(args => {
    args[0].meta = [
        {
            property: 'og:image',
            content: `${environment_url}/images/logos/my_logo.png`,
        },
        {
            property: 'og:image:width',
            content: '1200',
        },
        {
            property: 'og:image:height',
            content: '1200',
        },
    ];
    return args;
});

**Comment by raftx24** [comment]
yes, you can also edit `vendor/laravel-enso/core/stubs/production-index.blade.stub`, this file is used by vue-cli to generate final index, you can change it and add your custom meta tag to it.
if you want to use this solution you may need to change [this](https://github.com/laravel-enso/enso/blob/22c91afd8b76ca75134c86c384d14614e190fca1/client/vue.config.js#L12) too.

**Comment by curtisdelicata** [comment]
Modifying stub and changing location to use new stub file works perfect. Many thanks.
