### ISSUE TITLE
Support redirecting to self

### ISSUE THREAD

**Issue by jlsjonas** [enso-ui/ui#7]
This is  a **feature request**.

### Prerequisites
yes

### Description

Support a backend-redirect to the same route, with different parameters

### Steps to Reproduce
1. Have a store() form method on back-end return to the same (create) route, with a custom parameter
2. Submit the form

### Expected behavior

Router to _redirect_ to the route with the custom parameter available

### Actual behavior

Nothing

**Comment by aocneanu** [comment]
Doesn't this already happen if you redirect to the same route and add something to the `param` from the controller's `store` method?

**Comment by jlsjonas** [comment]
I just double-checked and it does not; also see https://github.com/vuejs/vue-router/issues/1012
(also not if I make `<router-view` use `$route.params` as key instead of `$route.path`)

Do note that `beforeRouteUpdate` also isn't triggered, at least not in `Edit.vue`

I'm using `@submit` as a workaround for now (my current usage just needs an update of certain data) but it can cause unexpected behaviour.
