### ISSUE TITLE
Open content in new tab/window

### ISSUE THREAD

**Issue by robbykrlos** [enso-ui/ui#75]
This is  a **question**.

Hi,

I've searched the documentation, and enso-ui/ui and laravel-enso/enso open and closed tickets but did not find any info on opening content in new tab. (_blank). I know this might not be something that an SPA needs...

I have a request to open some text (bigger description, like a help doc) inside a new tab, not in the same page, not using modals.

I thought to start this from scratch, but first to ask some questions, maybe there is an example or some support.

Appreciate your support,
Thanks,

**Comment by aocneanu** [comment]
Hi @robbykrlos, [pure js](https://github.com/enso-ui/companies/blob/master/src/bulma/pages/companies/Index.vue#L24)

**Comment by robbykrlos** [comment]
> Hi @robbykrlos, [pure js](https://github.com/enso-ui/companies/blob/master/src/bulma/pages/companies/Index.vue#L24)

Cool, thanks!

**Comment by robbykrlos** [comment]
We've managed to do a simple implementation of this - in order to open some kind of textual representation of some data, inside a pop-up window like this:
Instead of 
```vue
 this.$router.push({....
```

```vue
let myRoute = this.$router.resolve({
                name: 'myroute.index',
                params: {
                    param1: someValue,
                    param2: someValue
                },
            });

            window.open(myroute.href, '_blank', 'menubar=0');
```

Just in case anyone out there is looking for some easy solution
