### ISSUE TITLE
User preferences are not longer working (4.9.0)

### ISSUE THREAD

**Issue by robbykrlos** [enso-ui/ui#87]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Until Laravel Enso 4.8.2, user session preferences were remembered. Take example of table search words, or columns selected for visibility. 

Now, on 4.9.0, locally, and on https://www.laravel-enso.com preferences are not kept, and changing the menu is acting as a Reset (for tables). Similarly on Forms, the "changes" are lost.

**Comment by aocneanu** [comment]
Are you sure that you are using the latest table (UI) package?

**Comment by robbykrlos** [comment]
> Are you sure that you are using the latest table (UI) package?

My bad, not the latest UI packages.

Works now with `yarn upgrade` today 2022-01-28.

Sorry.
