### ISSUE TITLE
User profile header component missing

### ISSUE THREAD

**Issue by robbykrlos** [enso-ui/ui#88]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

On https://www.laravel-enso.com/ you are missing the upper right user profile - I cannot logout (tested on Firefox and Edge).

![image](https://user-images.githubusercontent.com/16973022/151355616-df0f93f2-fd74-4ec7-bf9a-c3fef168a1a1.png)

**Comment by aocneanu** [comment]
did you run yarn upgrade yesterday or today?

**Comment by robbykrlos** [comment]
Locally I think I'm 1 week late. I always forget to check on UI independent updates, sorry. Will double-check with latest, and close my tickets if fixed. 

Screenshot is taken on your website, today around 14:00.

**Comment by robbykrlos** [comment]
> did you run yarn upgrade yesterday or today?

When I reported the issue, I only referred to the https://www.laravel-enso.com/. 

On our side the user profile / avatar was in place, but again, we were some days behind with UI...

I will assume then that this is a deployment delay on your demo server and the issue is fixed.

**Comment by aocneanu** [comment]
we will create a new release earlier next week (@gandesc )
